### ISSUE TITLE
Stylear

### ISSUE THREAD

**Issue by ngarbezza** [ngarbezza/pim-pam-pum#18]
- login
- listado de eventos

**Comment by rochiAmaya** [comment]
agregar bootstrap con ember :
ember install:addon ember-bootstrap

**Comment by rochiAmaya** [comment]
$ bower install --save-dev bootstrap-sass-official
$ npm install --save-dev broccoli-sass

**Comment by ngarbezza** [comment]
datepicker: https://github.com/soulim/ember-cli-bootstrap-datepicker
