### ISSUE TITLE
agregar invitados a un eventos vista

### ISSUE THREAD

**Issue by rochiAmaya** [ngarbezza/pim-pam-pum#26]
librería de autocomplete: https://github.com/toranb/ember-cli-auto-complete

**Comment by rochiAmaya** [comment]
Definir si se pueden invitar a usuarios no legueados en la app

**Comment by ngarbezza** [comment]
muchísimos problemas con https://github.com/toranb/ember-cli-auto-complete

intentando usar https://github.com/aupac/ember-aupac-typeahead
