### ISSUE TITLE
Deploy automatico heroku

### ISSUE THREAD

**Issue by rochiAmaya** [ngarbezza/pim-pam-pum#36]
Deployar los cambios del branch master de manera automatica

**Comment by ngarbezza** [comment]
ya tenemos deploy automático a apps separadas de producción y staging, más detaller en la wiki (https://github.com/ngarbezza/pim-pam-pum/wiki/Deployment)

Server de producción: http://pim-pam-pum.herokuapp.com/
Server de staging: http://ppp-stg.herokuapp.com/login

**Comment by ngarbezza** [comment]
parece funcionar bien :)
